---
  - name: Copy bash script to attach volume
    ansible.builtin.copy:
      src: ./attach-source-ebs.sh
      dest: /home/ec2-user/attach-source-ebs.sh
      owner: ec2-user
      group: ec2-user
      mode: '0744'

  - name: Copy bash script to prepare volume
    ansible.builtin.copy:
      src: ./prep-ebs-source.sh
      dest: /home/ec2-user/prep-ebs-source.sh
      owner: ec2-user
      group: ec2-user
      mode: '0744'

  - name: Run attachment script
    ansible.builtin.shell: |
      /home/ec2-user/attach-source-ebs.sh

  - name: Run preparation script
    ansible.builtin.shell: |
      /home/ec2-user/prep-ebs-source.sh
...
