# source EC2 playbook
---
- name: Initialise PostgreSQL Source EBS
  hosts: localhost
  gather_facts: false

  tasks:
  - name: set var file name
    ansible.builtin.set_fact:
      var_file: "vars_{{ lookup('env', 'ENVIRONMENT') }}.yml"
      target_ebs: "source"

  - name: load variables
    ansible.builtin.include_vars:
      file: "{{ var_file }}"

  - name: get AWS session token
    community.aws.sts_session_token:
      duration_seconds: 3600
    register: session_credentials

  - name: switch role credentials
    community.aws.sts_assume_role:
      access_key: "{{ session_credentials.sts_creds.access_key }}"
      secret_key: "{{ session_credentials.sts_creds.secret_key }}"
      session_token: "{{ session_credentials.sts_creds.session_token }}"
      role_arn: "{{ lookup ('env', 'AWS_ROLE_ARN') }}"
      role_session_name: "s-devops"
    register: assumed_role

  - name: copy key file from S3
    amazon.aws.s3_object:
      bucket: "ds-{{ lookup('env', 'ENVIRONMENT') }}-kpf-administration"
      object: "{{ key_name }}"
      dest: "{{ key_name }}"
      mode: get

  - name: initialise environment
    ansible.builtin.include_tasks:
      file: ./includes/init-env.yml

