---
  - name: set credential key
    ansible.builtin.set_fact:
      credential_key: "{{ lookup('env', 'SECRETS_PATH') }}"

  - name: get db secrets
    ansible.builtin.set_fact:
      root_password: "{{ lookup('amazon.aws.aws_secret', credential_key + '.root_password', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, nested=true, on_denied='error') }}"
      admin_user: "{{ lookup('amazon.aws.aws_secret', credential_key + '.admin_user', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, nested=true, on_denied='error') }}"
      admin_pass: "{{ lookup('amazon.aws.aws_secret', credential_key + '.admin_pass', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, nested=true, on_denied='error') }}"
      network_cidr: "{{ lookup('amazon.aws.aws_secret', credential_key + '.network_cidr', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, nested=true, on_denied='error') }}"

  - name: get network information
    ansible.builtin.set_fact:
      vpc_id: "{{ lookup('amazon.aws.ssm_parameter', prefix_network_keys + '/vpc_id', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, on_denied='error') }}"
      subnet_id_a: "{{ lookup('amazon.aws.ssm_parameter', prefix_network_keys + '/private_subnet_2a_id', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, on_denied='error') }}"
      subnet_id_b: "{{ lookup('amazon.aws.ssm_parameter', prefix_network_keys + '/private_subnet_2b_id', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, on_denied='error') }}"
      subnet_db_id_a: "{{ lookup('amazon.aws.ssm_parameter', prefix_network_keys + '/private_db_subnet_2a_id', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, on_denied='error') }}"
      subnet_db_id_b: "{{ lookup('amazon.aws.ssm_parameter', prefix_network_keys + '/private_db_subnet_2b_id', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, on_denied='error') }}"
      public_subnet_id: "{{ lookup('amazon.aws.ssm_parameter', prefix_network_keys + '/public_subnet_2a_id', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, on_denied='error') }}"

  - name: template instance role source
    vars:
      s3_deployment_bucket: "ds-{{ lookup( 'env', 'ENVIRONMENT') }}-deployment-source"
      s3_deployment_root: "{{ s3_deployment_root }}"
      s3_kpf_bucket: "ds-{{ lookup( 'env', 'ENVIRONMENT') }}-kpf-administration"
    template:
      src: "./templates/instance-role-policy.json.j2"
      dest: "./instance-role-policy.json"
      force: yes

  - name: create deployment policy
    community.aws.iam_managed_policy:
      access_key: "{{ assumed_role.sts_creds.access_key }}"
      secret_key: "{{ assumed_role.sts_creds.secret_key }}"
      session_token: "{{ assumed_role.sts_creds.session_token }}"
      policy_name: "{{ deployment_policy_name }}"
      policy: "{{ lookup('file', './instance-role-policy.json') }}"
      state: "present"
    register: s3_policy

  - name: create postgres IAM role
    community.aws.iam_role:
      access_key: "{{ assumed_role.sts_creds.access_key }}"
      secret_key: "{{ assumed_role.sts_creds.secret_key }}"
      session_token: "{{ assumed_role.sts_creds.session_token }}"
      name: "{{ iam_role_name }}"
      region: "{{ region }}"
      assume_role_policy_document: "{{ lookup('file', './ec2-role-policy.json') }}"
      managed_policies: ["{{ s3_policy.policy.arn }}", "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"]
      create_instance_profile: yes
      delete_instance_profile: yes
      purge_policies: yes
      state: "present"
    register: ec2_iam_role

  - name: create security group - allowing updates and downloads
    amazon.aws.ec2_security_group:
      access_key: "{{ assumed_role.sts_creds.access_key }}"
      secret_key: "{{ assumed_role.sts_creds.secret_key }}"
      session_token: "{{ assumed_role.sts_creds.session_token }}"
      name: "{{ ec2_sg_name }}"
      description: "security group allowing updates and downloads"
      region: "{{ region }}"
      vpc_id: "{{ vpc_id }}"
      rules:
        - proto: "tcp"
          from_port: 22
          to_port: 22
          cidr_ip: "0.0.0.0/0"
          rule_desc: "allow incoming ssh connections"
        - proto: "tcp"
          from_port: 1024
          to_port: 65535
          cidr_ip: "0.0.0.0/0"
          rule_desc: "for updates and downloads"
      rules_egress:
        - proto: "tcp"
          from_port: 80
          to_port: 80
          cidr_ip: "0.0.0.0/0"
          rule_desc: "allow updates and downloads"
        - proto: "tcp"
          from_port: 443
          to_port: 443
          cidr_ip: "0.0.0.0/0"
          rule_desc: "allow updates and downloads"
        - proto: "tcp"
          from_port: 1024
          to_port: 65535
          cidr_ip: "0.0.0.0/0"
          rule_desc: "allow replies"
      state: "present"
    register: ec2_sec_group

  - name: copy key file from S3
    amazon.aws.s3_object:
      access_key: "{{ assumed_role.sts_creds.access_key }}"
      secret_key: "{{ assumed_role.sts_creds.secret_key }}"
      session_token: "{{ assumed_role.sts_creds.session_token }}"
      bucket: "ds-{{ lookup('env', 'ENVIRONMENT') }}-kpf-administration"
      object: "{{ lookup('env', 'KEY_NAME') }}"
      dest: "{{ lookup('env', 'KEY_NAME') }}"
      mode: get

  - name: set permission for key file
    ansible.builtin.file:
      path: "{{ lookup('env', 'KEY_NAME') }}"
      state: file
      mode: '0600'
...
