---
  - name: get linux2 AMI
    amazon.aws.ec2_ami_info:
      access_key: "{{ assumed_role.sts_creds.access_key }}"
      secret_key: "{{ assumed_role.sts_creds.secret_key }}"
      session_token: "{{ assumed_role.sts_creds.session_token }}"
      owners: amazon
      region: "{{ region }}"
      filters:
        name: "amzn2-ami-hvm*"
    register: findami

  - name: set latest AMI
    set_fact:
      latest_ami: >
        {{ findami.images | sort(attribute='creation_date') | last }}

  - name: set secrets
    vars:
      secret_data: "{{ lookup('amazon.aws.aws_secret', '{{ postgres_credentials_key }}', region=region, aws_access_key=assumed_role.sts_creds.access_key, aws_secret_key=assumed_role.sts_creds.secret_key, aws_session_token=assumed_role.sts_creds.session_token, on_denied='warn') | from_json }}"
    set_fact:
        root_password: "{{ secret_data.root_password }}"
        admin_user: "{{ secret_data.admin_user }}"
        admin_pass: "{{ secret_data.admin_pass }}"
        repl_user: "{{ secret_data.repl_user }}"
        repl_pass: "{{ secret_data.repl_pass }}"
        network_cidr: "{{ secret_data.network_cidr }}"

#  - name: get db secrets
#    ansible.builtin.set_fact:
#      root_password: "{{ lookup('amazon.aws.aws_secret', postgres_credentials_key + '.root_password', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, nested=true, on_denied='error') }}"
#      admin_user: "{{ lookup('amazon.aws.aws_secret', postgres_credentials_key + '.admin_user', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, nested=true, on_denied='error') }}"
#      admin_pass: "{{ lookup('amazon.aws.aws_secret', postgres_credentials_key + '.admin_pass', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, nested=true, on_denied='error') }}"
#      repl_user: "{{ lookup('amazon.aws.aws_secret', postgres_credentials_key + '.repl_user', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, nested=true, on_denied='error') }}"
#      repl_pass: "{{ lookup('amazon.aws.aws_secret', postgres_credentials_key + '.repl_pass', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, nested=true, on_denied='error') }}"
#      network_cidr: "{{ lookup('amazon.aws.aws_secret', postgres_credentials_key + '.network_cidr', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, nested=true, on_denied='error') }}"

  - name: get network information
    ansible.builtin.set_fact:
      vpc_id: "{{ lookup('amazon.aws.ssm_parameter', prefix_network_keys + '/vpc_id', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, on_denied='error') }}"
      subnet_id_a: "{{ lookup('amazon.aws.ssm_parameter', prefix_network_keys + '/private_db_subnet_2a_id', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, on_denied='error') }}"
      subnet_id_b: "{{ lookup('amazon.aws.ssm_parameter', prefix_network_keys + '/private_db_subnet_2b_id', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, on_denied='error') }}"
      public_subnet_id: "{{ lookup('amazon.aws.ssm_parameter', prefix_network_keys + '/public_subnet_2a_id', access_key=assumed_role.sts_creds.access_key, secret_key=assumed_role.sts_creds.secret_key, session_token=assumed_role.sts_creds.session_token, on_denied='error') }}"

  - name: create temp ssh key
    community.crypto.openssh_keypair:
      path: "/tmp/{{ key_name }}"
      size: 2048
      comment: "temp@nationalarchives.gov.uk"
      mode: '644'
      state: "present"
      type: "rsa"

  - name: create key pair for instance
    amazon.aws.ec2_key:
      access_key: "{{ assumed_role.sts_creds.access_key }}"
      secret_key: "{{ assumed_role.sts_creds.secret_key }}"
      session_token: "{{ assumed_role.sts_creds.session_token }}"
      name: "{{ key_name }}"
      key_material: "{{ lookup('file', '/tmp/' + key_name + '.pub') }}"
      state: "present"

  - name: template userdata source
    vars:
      s3_deployment_bucket: "{{ s3_deployment_bucket }}"
      s3_deployment_root: "{{ s3_deployment_root }}"
    template:
      src: "./templates/instance-role-policy.json.j2"
      dest: "./instance-role-policy.json"
      force: yes

  - name: create deployment policy
    community.aws.iam_managed_policy:
      access_key: "{{ assumed_role.sts_creds.access_key }}"
      secret_key: "{{ assumed_role.sts_creds.secret_key }}"
      session_token: "{{ assumed_role.sts_creds.session_token }}"
      policy_name: "{{ deployment_policy_name }}"
      policy: "{{ lookup('file', './instance-role-policy.json') }}"
      state: "present"
    register: s3_policy

  - name: create postgres IAM role
    community.aws.iam_role:
      access_key: "{{ assumed_role.sts_creds.access_key }}"
      secret_key: "{{ assumed_role.sts_creds.secret_key }}"
      session_token: "{{ assumed_role.sts_creds.session_token }}"
      name: "{{ iam_role_name }}"
      region: "{{ region }}"
      assume_role_policy_document: "{{ lookup('file', './templates/ec2-role-policy.json') }}"
      managed_policies: ["{{ s3_policy.policy.arn }}", "arn:aws:iam::aws:policy/SecretsManagerReadWrite"]
      create_instance_profile: yes
      delete_instance_profile: yes
      purge_policies: yes
      state: "present"
    register: ec2_iam_role

  - name: create security group - allowing updates and downloads
    amazon.aws.ec2_security_group:
      access_key: "{{ assumed_role.sts_creds.access_key }}"
      secret_key: "{{ assumed_role.sts_creds.secret_key }}"
      session_token: "{{ assumed_role.sts_creds.session_token }}"
      name: "{{ ec2_sg_name }}"
      description: "security group allowing updates and downloads"
      region: "{{ region }}"
      vpc_id: "{{ vpc_id }}"
      rules:
        - proto: "tcp"
          from_port: 22
          to_port: 22
          cidr_ip: "0.0.0.0/0"
          rule_desc: "allow incoming ssh connections"
        - proto: "tcp"
          from_port: 1024
          to_port: 65535
          cidr_ip: "0.0.0.0/0"
          rule_desc: "for updates and downloads"
      rules_egress:
        - proto: "tcp"
          from_port: 80
          to_port: 80
          cidr_ip: "0.0.0.0/0"
          rule_desc: "allow updates and downloads"
        - proto: "tcp"
          from_port: 443
          to_port: 443
          cidr_ip: "0.0.0.0/0"
          rule_desc: "allow updates and downloads"
        - proto: "tcp"
          from_port: 1024
          to_port: 65535
          cidr_ip: "0.0.0.0/0"
          rule_desc: "allow replies"
      state: "present"
    register: ec2_sec_group

  - name: template userdata source
    vars:
      root_password: "{{ root_password }}"
      admin_user: "{{ admin_user }}"
      admin_password: "{{ admin_password }}"
      repl_user: "{{ repl_user }}"
      repl_password: "{{ repl_password }}"
      network_cidr: "{{ network_cidr }}"
      ebs_name: "{{ ebs_tag_name }}"
    template:
      src: "./templates/userdata-source.sh.j2"
      dest: "./userdata.sh"
      force: yes
...
